default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rhizo_development

test:
  <<: *default
  database: rhizo_test

production:
  <<: *default
  database: rhizo_production
  username: rhizo
  password: <%= ENV['RHIZO_DATABASE_PASSWORD'] %>
